Hw1
rprtr258/program-architecture-homeworks pull request #1
Opened 2020-09-29 09:11 UTC by rprtr258

2020-09-29 15:41 UTC, yurii-litvinov requested changes
14 коммитов с комментарием "Fix", так никогда не найти нужный :) Ну и всё-таки кое-какие вопросы/замечания ещё остались. Давайте будет 9 из 10 баллов и можно доисправлять, чтобы было 10.

2020-09-29 15:41 UTC, yurii-litvinov commented on hw1.md
> +![обновите бровзер](img/hw1.svg "Диаграмма классов")
ErrorCode, судя по всему, enum, он рисуется так: https://www.uml-diagrams.org/data-type.html#enumeration

2020-09-29 15:41 UTC, yurii-litvinov commented on hw1.md
> +![обновите бровзер](img/hw1.svg "Диаграмма классов")
И EnvironmentVars у Parser дублирует ассоциацию, что нехорошо. По стандарту получается, что у Parser два поля типа EnvironmentVars --- одно поле environment, одно поле, подразумеваемое ассоциацией с классом EnvironmentVars

2020-09-29 15:41 UTC, yurii-litvinov commented on hw1.md
> +	    if (varname in line) {
Примерно. Всё-таки нужен "$" для подстановки, и на самом деле двойные кавычки для постановки не обязательны (в примерах было `echo $x` без всяких кавычек). Может, правда, у вас переменные прямо с долларами и хранятся, но это не очевидно из описания

2020-09-29 15:41 UTC, yurii-litvinov commented on hw1.md
> +После этого не остается неподставленных переменных, и даже, если появятся пробелы, методы `parseCommand`, `parsePipeline`, `parseAssignment` смогут разделить строку по пробелам.
А если появятся кавычки? :) И ещё я так и не понял, когда выполняется этот код. Даже isPipeline, наверное, сначала должен выполнить подстановку (потому что а вдруг в переменной пайп спрятан, или такое запрещено?). Или эта функция вызывается из всех остальных перед их выполнением?

2020-09-29 15:41 UTC, yurii-litvinov commented on hw1.md
> +В `cmd` записывается результат метода `Parser.parse`. Эта переменная хранит экземпляр интерфейса `Executable`, а значит является либо экземпляром `PipedCommand`, либо экземпляром одного из наследнико
В настоящем bash-е команда принимает входной поток. В начале пайпа это stdin, дальше --- stdout предыдущей команды, вроде как. Это позволяет вообще не думать внутри команды, пайпы у нас или нет, а всё, что делает пайп --- "склеивает" выходной и входной потоки двух команд и запускает сами команды (в настоящем bash параллельно, но у нас можно и последовательно). 

Это скорее к сведению, можно оставить и как у вас, why not.

2020-09-30 17:55 UTC, ZaicevDima commented on hw1.md
> +![обновите бровзер](img/hw1.svg "Диаграмма классов")
Юрий Викторович, а если исправить только диаграмму можно рассчитывать на +1 балл?

2020-09-30 18:21 UTC, yurii-litvinov commented on hw1.md
> +![обновите бровзер](img/hw1.svg "Диаграмма классов")
Мм, нет, надо ещё пояснить и в тексте про подстановки. Но там не надо всё переделывать, надо именно что пояснить.

2020-09-30 18:29 UTC, rprtr258 commented on hw1.md
> +![обновите бровзер](img/hw1.svg "Диаграмма классов")
Просто про подстановки оказывается, что все несколько сложнее, чем я думал изначально, в частности
```bash
> a=ec
> b=ho
> $a$b $a $b
ec ho
> 'ec''ho' 'ec' 'ho'
ec ho
> a="'ec'"
> b="'ho'"
> $a$b $a$b
ec: command not found
> echo $a $b
'ec' 'ho'
> a='|'
> echo abc $a cat
abc | cat
```
И поэтому подстановку переменных нужно строже специфицировать в требованиях. Про доллары могу сказать, что в коде подстановки должен добавляться символ доллара, могу добавить в псевдокод это.

2020-11-25 17:49 UTC, merged